### ISSUE TITLE
Change url of openlayers geocoder

### ISSUE THREAD

**Issue by brunob** [mapstraction/mxn#143]
We should use one the mapquest geocoder instead of the one hosted on openlayers servers.

http://open.mapquestapi.com/nominatim/ or http://open.mapquestapi.com/geocoding/

The first one "relies solely on data contributed to OpenStreetMap".

**Comment by gilesc50** [comment]
This has now been done, so this issue can be closed I think.

**Comment by vicchi** [comment]
I'm not so sure that this issue is linked to Pull Request #146.

Pull Request #146 was about MXN's use of `http://nominatim.openstreetmap.org/` which was throwing a 503 error and which provided a fix.

This issue is more about the accuracy of that geocoder, at least from my reading of it, and swapping out `http://nominatim.openstreetmap.org/` for one of the MQ geocoding APIs.

I think that we should really do some accuracy and coverage testing on all three geocoders and make a judgement call based on that testing. The question is ... who has time to do this? Not sure that I do right now.

**Comment by gilesc50** [comment]
I feel we can close this as we now have so many geocoders available including the mapquest one, so anyone preferring the mapquest one can use that.
