### ISSUE TITLE
Event "endPan" fires all the time with Google V3 layer

### ISSUE THREAD

**Issue by mjesun** [mapstraction/mxn#227]
The event should only fire when the pan finishes, but instead it triggers all the time you pan the map. It seems that the problem comes from being attached to the `center_changed` event for triggering the `endPan` event.

By removing this snippet:

``` js
google.maps.event.addListener(map, 'center_changed', function() {
    me.endPan.fire();
});
```

Which is located at https://github.com/mapstraction/mxn/blob/release-2.1/source/mxn.googlev3.core.js#L99, everything works fine. I can make a pull request if you want me to do so, but I'd like to ensure that this is the expected behavior first.

**Comment by vicchi** [comment]
Yup. That's a bug. Nicely spotted. Turns out there's no direct analog to the `endPan` event in the Google V3 API. You can detect the end of dragging, when the centre changes or when the bounds change. So I've trapped whether the map is being dragged and `endPan` now only fires at the end of any panning operation, be that dragging, panning from the pan/zoom control or other cause.

This is now fixed on the `release-2.1` branch; see commit 567b26d6443ddd16af048f605f176c83cd253b10.
