### ISSUE TITLE
Marker not working for Leaflet but working in open layers

### ISSUE THREAD

**Issue by kpvinay84** [mapstraction/mxn#231]
Hi,

I am trying to apply Marker to the map using leaflet (latest version) but it is throwing the below error.

Error: iconUrl not set in Icon options (see the docs).

I am using the below code: http://jsfiddle.net/x4rBQ/
<link href="http://leaflet.cloudmade.com/dist/leaflet.css" rel="stylesheet" type="text/css" />

<script src="http://leaflet.cloudmade.com/dist/leaflet.js" type="text/javascript"></script>

<script src="https://raw.github.com/mapstraction/mxn/master/source/mxn.js?(leaflet)" type="text/javascript"></script>

<div id="leaflet-map" style="height: 400px;"></div>

<script type="text/javascript">
    var map = new mxn.Mapstraction('leaflet-map', 'leaflet'); 
        var latlon = new mxn.LatLonPoint(51.50733, -0.12769);
        var marker1 = new mxn.Marker(latlon);
        map.addMarker(marker1);
        map.setCenterAndZoom(latlon, 10);
</script>

It is working fine in openlayers though the code is below: http://jsfiddle.net/WUTs6/

<script src="http://openlayers.org/api/OpenLayers.js"></script>

<script src="https://raw.github.com/mapstraction/mxn/master/source/mxn.js?(openlayers)" type="text/javascript"></script>

<div id="openlayers-map" style="height: 400px;"></div>

<script type="text/javascript">
    var map = new mxn.Mapstraction('openlayers-map', 'openlayers'); 
        var latlon = new mxn.LatLonPoint(51.50733, -0.12769);
        var marker1 = new mxn.Marker(latlon);
        map.addMarker(marker1);
        map.setCenterAndZoom(latlon, 10);
</script>

You can preview it using the jsfiddle links i have provided.

**Comment by vicchi** [comment]
IIRC, this has been fixed in the `release-2.1` branch but is still a bug in `master` as the next release hasn't yet been released.

Can you try again but this time include `mxn.js` from the release branch, either by cloning the current repository locally (preferable) or, for testing, from the release branch at `https://raw.github.com/mapstraction/mxn/release-2.1/source/mxn.js`.

-Gary

**Comment by kpvinay84** [comment]
Yes it is working fine when i use release-2.1 mxn.js
Hopefully it will be in Master soon.

**Comment by crhode** [comment]
This seems still to be a problem.  Any prognosis?

**Comment by vicchi** [comment]
The `master` branch currently holds Mapstraction v2.0.18, but this release is no longer being actively maintained; all efforts are focused on the forthcoming v3.0 release.

Leaflet's marker API changed with Leaflet v0.4 in July 2012 (https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) and as a result, this is still a bug on `master` and in v2.0.18. It has been fixed on both the `release-2.1` and `release-3.0` branches via Pull Request #213.

I don't expect the `master` branch to have this fix applied retrospectively, due to the focus on getting v3.0 of Mapstraction out of the door.
