### ISSUE TITLE
Rules or steps to add new functions?

### ISSUE THREAD

**Issue by icebergdelphi** [mapstraction/mxn#262]
Hi all, anybody can help me ?
How steps or rules, do i follows to add new functions to the Mapstraction API? i'd like to add a editable Polygons function. Thanks.

**Comment by vicchi** [comment]
Take a look at the Contributing guidelines first ... https://github.com/mapstraction/mxn/wiki/Contributing

Then, consider whether your new functionality is provider independent or not.

If it is (in other words, it doesn't need any native provider API calls) then it needs to live in `mxn.core.js`.

If it isn't (in other words, you're calling provider specific API calls) then it needs to live in each of the `mxn.[provider].core.js` files so that it works across all the supported mapping API providers.

Then make sure the code builds cleanly via the project's ANT build script and, if warranted, add some example code.

Finally, submit a pull request.

Sounds easy doesn't it? It's probably not. But we'll help where we can.

-Gary
