### ISSUE TITLE
The marker methods 'show' and 'hide' do not work for openlayers in version 3.0.20

### ISSUE THREAD

**Issue by doppi** [mapstraction/mxn#269]
The subject describes the problem.
To reproduce it, please see this html code:
https://gist.github.com/doppi/6cc026a18ffb771f0c71

**Comment by vicchi** [comment]
Fixed in `release-3.0` branch; see commit 7bf260d3308e77f0a8118a87148caf602bf075b1. This fix isn't currently reflected via http://mapstraction.com/mxn/build/dev/, this will be updated later today, but for now if you have a local fork of the `release-3.0` branch you should see the change and it should be working. It is on my local install.

**Comment by vicchi** [comment]
Just updated mapstraction.com with RC5 ... http://mapstraction.com/mxn/build/dev/mxn.js and http://mapstraction.com/mxn/build/3.0.0-RC5/mxn.js now reflect the latest cut of the `release-3.0` branch.

**Comment by doppi** [comment]
Thank you I tried the new version, but the show/hide methods seem to affect all markers and not only the marker object you are invoking the method for...
Try this code to see for yourself:
https://gist.github.com/doppi/6068792

**Comment by vicchi** [comment]
You're right. Somehow it looks like the (recent) pull request that moved OpenLayers markers to use vectors has the side effect that all markers share the same layer. This is not good. I'll take a look at this but it's going to need some investigation and I'm on vacation in about 3 hours time, so it'll be a couple of weeks before I can give this some time. In the meantime, I'll reopen this issue.

**Comment by gilesc50** [comment]
Ok I’ll sort this one – enjoy your time off.

Giles
