### ISSUE TITLE
leaflet not loading

### ISSUE THREAD

**Issue by philipzae** [mapstraction/mxn#285]
I'm getting the following error "iconUrl not set in Icon options (see the docs)." when trying to load leaflet, which is coming from with leaflet.js. I tried the same code with openlayers and it worked fine.

**Comment by philipzae** [comment]
The leaflet map loads fine and can function, but the marker wont appear on the map as the error gets tripped.

**Comment by gilesc50** [comment]
If you are using the master branch, try using the release-2.1 branch that should fix the issue

**Comment by vicchi** [comment]
The `master` branch currently holds Mapstraction v2.0.18, but this release is no longer being actively maintained; all efforts are focused on the forthcoming v3.0 release.

Leaflet's marker API changed with Leaflet v0.4 in July 2012 (https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) and as a result, this is still a bug on `master` and in v2.0.18. It has been fixed on both the `release-2.1` and `release-3.0` branches via Pull Request #213.

I don't expect the `master` branch to have this fix applied retrospectively, due to the focus on getting v3.0 of Mapstraction out of the door.

**Comment by philipzae** [comment]
how can i get a hold of release 2.1

**Comment by vicchi** [comment]
It's on its own `release-2.1` branch. Either fork the repository and check out the branch or go to https://github.com/mapstraction/mxn/tree/release-2.1 and click on the _Download ZIP_ button.

A word of caution though; MXN v2.1 was never released. It should be stable but hasn't gone through a full release test. v2.1 morphed into v3.0 due to the number of changes/additions that were going into the code base.
