### ISSUE TITLE
Mapstraction from google SVN fails.

### ISSUE THREAD

**Issue by antani** [mapstraction/mxn#53]
I am trying to use mapstraction from google svn as follows :
script type="text/javascript" charset="utf-8" src="http://mapstraction.googlecode.com/svn/trunk/source/mxn.js?(google)"></script
From yesterday, when I load the page, I am asked username and password for Google SVN repository for mapstraction javascript.
Even Mapstraction demos are failing with the same error.

**Comment by dezfowler** [comment]
The Google Code repo is the old one and very out of date. I will update the Sandbox demos soon so that they use github instead. You should do the same, either point at the github repo or download one of the builds and host it yourself. After I update the Sandbox I will be deleting the Google Code repo again as it just causes confusion.

**Comment by antani** [comment]
Thanks, Can you tell me how to point to github repo from code ? also please let me know how many .js need to be added and hosted for mapstraction to work. I added mxn.js and mxn-core.js but mapstraction fails with errors. a write up on this would be very helpful
